// `prettier` does not yet support `import type`

import type React from "react";
import {useCallback, useEffect, useMemo, useRef, useSyncExternalStore} from "react";

type URLState = [URL, (value: React.SetStateAction<URL>, noHistoryEntry?: boolean) => void];

interface PendingUrlUpdate {
    url: URL;
    shouldPush: boolean;
}

// `info` is not persisted in history; it only identifies the navigate event
// synchronously generated by this hook.
const browserUrlNavigationInfo = {};

function getBrowserUrl(): string {
    return window.navigation.currentEntry?.url ?? window.location.href;
}

function subscribeToBrowserUrl(onStoreChange: () => void): () => void {
    window.navigation.addEventListener("currententrychange", onStoreChange);
    return () => window.navigation.removeEventListener("currententrychange", onStoreChange);
}

export function useBrowserUrl(): URLState {
    const href = useSyncExternalStore(subscribeToBrowserUrl, getBrowserUrl);
    const url = useMemo(() => new URL(href), [href]);
    const pendingUrlUpdate = useRef<PendingUrlUpdate | undefined>(undefined);

    useEffect(() => {
        const listener = (event: NavigateEvent) => {
            if (event.canIntercept && event.info === browserUrlNavigationInfo) {
                // These navigations only update URL-backed state. Preserve the user's
                // current focus and scroll position while making them same-document.
                event.intercept({
                    focusReset: "manual",
                    scroll: "manual",
                });
            }
        };
        window.navigation.addEventListener("navigate", listener);
        return () => window.navigation.removeEventListener("navigate", listener);
    }, []);
    const setUrl = useCallback((action: React.SetStateAction<URL>, noHistoryEntry?: boolean) => {
        let pending = pendingUrlUpdate.current;
        if (!pending) {
            pending = {
                url: new URL(getBrowserUrl()),
                shouldPush: false,
            };
            pendingUrlUpdate.current = pending;
            queueMicrotask(() => {
                const update = pendingUrlUpdate.current;
                pendingUrlUpdate.current = undefined;
                if (update && update.url.href !== getBrowserUrl()) {
                    window.navigation.navigate(update.url.toString(), {
                        history: update.shouldPush ? "push" : "replace",
                        info: browserUrlNavigationInfo,
                    });
                }
            });
        }
        pending.url = typeof action === "function" ? action(pending.url) : action;
        pending.shouldPush ||= !noHistoryEntry;
    }, []);
    return [url, setUrl];
}

// Generate URLSearchParams from the URL hash and the URL search params,
// with the hash params taking precedence
function generateUrlSearchParams(url: URL): URLSearchParams {
    // Use a clone of the URLSearchParams to avoid mutating the original URLSearchParams
    const params = new URLSearchParams(url.search);
    const hashParams = new URLSearchParams(url.hash.slice(1));
    hashParams.forEach((value, key) => {
        params.set(key, value);
    });
    return params;
}

export function useUrlParam(
    urlState: URLState,
    key: string,
    noHistoryEntry?: boolean,
): [string | undefined, React.Dispatch<React.SetStateAction<string | undefined>>] {
    const [url, setUrl] = urlState;
    const searchParams = generateUrlSearchParams(url);
    const v = searchParams.get(key) ?? undefined;
    const set = useCallback(
        (action: React.SetStateAction<string | undefined>) => {
            setUrl((url) => {
                const searchParams = generateUrlSearchParams(url);
                const currentValue = searchParams.get(key) ?? undefined;
                let newValue: string | undefined;
                if (action instanceof Function) newValue = action(currentValue);
                else newValue = action;
                const newURL = new URL(url);
                if (newValue === undefined) {
                    searchParams.delete(key);
                } else {
                    searchParams.set(key, newValue);
                }
                // Delete all search parameters and move them to the hash to avoid
                // sending unnecessary data to the server
                newURL.search = "";
                newURL.hash = `#${searchParams.toString()}`;
                return newURL;
            }, noHistoryEntry);
        },
        [setUrl, key, noHistoryEntry],
    );
    return [v, set];
}
